baseurl = "http://devops.ge"
title = "DevOps.ge | Tornike Zedginidze"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "toko"
googleAnalytics = "UA-85259301-1"

[menu]
  [[menu.main]]
    name = "shelf"
    weight = 2
    url = "/shelf"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "mailto:tokozedg@gmail.com"
    
[params]
  Keywords = "key, aha"
  Description = "There are some words to describe your site"
  
  GithubID = "tokozedg"
  TwitterID = "Zedginidze"
  LinkedInID = "tokozedg"
  GoogleplusID = "101511740319661471581"
