baseurl = "http://devops.ge"
title = "toko"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "toko"
googleAnalytics = "UA-85259301-1"

[menu]
  [[menu.main]]
    name = "e-shelf"
    weight = 1
    url = "/shelf"

[params]
  GithubID = "tokozedg"
  TwitterID = "Zedginidze"
  LinkedInID = "tokozedg"
  GoogleplusID = "101511740319661471581"
