baseurl = "/"
title = "devops.ge"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "toko"
googleAnalytics = "UA-85259301-1"

[menu]
  [[menu.main]]
    name = "wiki"
    weight = 10
    url = "http://wiki.devops.ge"

  [[menu.main]]
    name = "library"
    weight = 4
    url = "/library"

  [[menu.main]]
    name = "setup"
    weight = 1
    url = "/setup"

[params]
  GithubID = "tokozedg"
  TwitterID = "Zedginidze"
  LinkedInID = "tokozedg"
  GoogleplusID = "101511740319661471581"
  KeyBase = "toko"
  homeDir = ""
